### ISSUE TITLE
Crash on Ubuntu 21.10

### ISSUE THREAD

**Issue by Ileca** [mrgoodvin/ranger_keybord#2]
Honestly, I don't know if I followed the instructions properly as I barely understood them.
I just wanted to remap the number row by adding:
> other_keys    = '&é"' + "'(-è_çà"
> en_keys       = '123' + "4567890"

Here is what I got
> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/home/ileca/.config/ranger/plugins/multiple_keyboard.py", line 99, in handle_input
    simple_key(keys)
  File "/home/ileca/.config/ranger/plugins/multiple_keyboard.py", line 66, in simple_key
    if chr(key) in other_keys_mm and not self.console.visible:
NameError: name 'other_keys_mm' is not defined

Ubuntu 21.10
Gnome 40.4.0
Wayland

**Comment by mrgoodvin** [comment]
Sorry for the late reply. Missed 'other_keys_mm' declaration.
It will be right:
other_keys = '&é"' + "'(-è_çà"
en_keys = '123' + "4567890"
other_keys_mm = ""
